name: Notify Deploy End
description: Notify success, failure, or cancellation to Google Chat with duration

runs:
  using: "composite"
  steps:
    - name: Success
      shell: bash
      run: |
        STATUS="${{ job.status }}"
        if [[ "$STATUS" == "success" ]]; then
          MESSAGE="成功"
        elif [[ "$STATUS" == "failure" ]]; then
          MESSAGE="失敗"
        elif [[ "$STATUS" == "cancelled" ]]; then
          MESSAGE="キャンセル"
        else
          echo "予期しないステータス: $STATUS"
        exit 1
        fi
        echo "message=${MESSAGE}"
